//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Net_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Travler
    {
        public int TravlerID { get; set; }
        [Required(ErrorMessage ="This Field is Required")]
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Departure { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Destination { get; set; }
        public string FlightClass { get; set; }
    }
}
